Code review
mariordgez/javascript-capstone pull request #25
Opened 2021-09-10 19:36 UTC by mariordgez

2021-09-10 21:46 UTC, sinansevgi requested changes
# Changes Required :recycle: 
------

Hi @mariordgez and @carlos-ssh , 

Good job so far!
Great work with tests. :clap: 
There are some issues that you still need to work on to go further but you are almost there!


 ## Required Changes ♻️

- [ ]  I couldn't find a link to the video presentation. Please provide the link in the pull request description. If you didn't record one please be sure you follow the below suggestions while recording one
 - You should record a video presenting the features of the project.
 - The maximum length of the video should be 5 minutes.
 - The video should contain a clear and objective description of the project in professional English. The topic and purpose of the project should be made clear.
 - All of the team members should appear in the video and talk about the project.
 - The video should contain a highlight about a piece of the code that you find interesting or is proud of making.
_Please check the inline comments for my suggestions_ :arrow_down:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Happy Hacking! :computer: 

-----

You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgi

------

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-10 21:46 UTC, sinansevgi commented on src/modules/buildShows.js
> +      window.location.reload();
[Optional]

- [ ] It will be better if you just update like count instead of refreshing the page.

2021-09-10 21:46 UTC, sinansevgi commented on tests/like-counter.test.js
> +});
[Optional]
- [ ] It will be better if you move tests for showsCount to its own file too.

2021-09-10 22:30 UTC, mariordgez commented
All changes were made according to code review, thanks for the feedback!

2021-09-11 00:08 UTC, sinansevgi approved these changes
# Approved :heavy_check_mark: 

Hi again team, 

Great work on making requested changes.
Your project is complete!  
Congratulations! 🎉

You can merge this pull request and continue with your journey :wave: 


Happy Hacking! :computer: 

-----

You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgi


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-11 00:16 UTC, merged